### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by xJon** [Red-Studio-Ragnarok/ReCrystallized-Wing#10]
Doesn't work on right click, prints this error into the server log: https://mclo.gs/CUZkw8o

**Comment by xJon** [comment]
Resetting their spawn (by sleeping in a different bed) worked, but upon breaking that new bed it stopped working again with a different error in the server log: https://mclo.gs/ZGVwZfg

**Comment by xJon** [comment]
I'm guessing that there's no code to fall back to world spawn in the case a player set a new spawn point in a bed that is then broken.

**Comment by Desoroxxx** [comment]
> I'm guessing that there's no code to fall back to world spawn in the case a player set a new spawn point in a bed that is then broken.

This could indeed be true, although I assume vanilla should do that on its own, but then again vanilla doesn't always do things correctly

**Comment by xJon** [comment]
Testing in a separate world, I can confirm there is no fall back to world spawn once the bed is broken.

**Comment by Desoroxxx** [comment]
Thanks

**Comment by Desoroxxx** [comment]
Fixed in 2.0
